### ISSUE TITLE
Failed patching of nginx.conf.web.https.template zimbra 8.8.8

### ISSUE THREAD

**Issue by eN0Rm** [jjakob/certbot-zimbra#1]
I've resumitted the issue here. Thanks for enabling issues. 

Let me know if there are more info I can provide. 

```
root@zimbra03-test:~/certbot-zimbra# ./certbot_zimbra.sh 
Certbot-Zimbra v0.3 - https://github.com/jjakob/certbot-zimbra
Detected Zimbra 8.8.8
Using zimbra03-test.copyleft.no ('zmhostname') as domain for certificate.
Making a backup of nginx templates in /opt/zimbra/conf/nginx/templates.20180531_124510
checking file nginx.conf.web.http.default.template
checking file nginx.conf.web.https.default.template
checking file nginx.conf.web.http.template
/usr/bin/patch: **** malformed patch at line 37: diff -Naur templates.20180530_213444/nginx.conf.web.https.template templates/nginx.conf.web.https.template

Patching test failed! Please file a bug with the output above to https://github.com/YetOpen/certbot-zimbra/issues/new
```

**Comment by eN0Rm** [comment]
This is line 37 in templates/nginx.conf.web.https.template

    ${web.login.upstream.disable}     if ($mailhostport != 80) {   # standard HTTP port, do not replace

**Comment by jjakob** [comment]
Can you provide the output of `zmcontrol -v`? I'm thinking you're on a different minor version/patch level of 8.8.8 than me.
Can you wait for me to replace the patching code with a sed variant, that should be version-agnostic. I'm busy doing other stuff ATM so expect it to be in a day or so.

**Comment by eN0Rm** [comment]
Release 8.8.8.GA.2009.UBUNTU16.64 UBUNTU16_64 FOSS edition, Patch 8.8.8_P4.

**Comment by eN0Rm** [comment]
Sure, I can wait.

**Comment by eN0Rm** [comment]
I can add that I'm testing this on a test-zimbra-install that uses self-signed certs and that did not use Letsencrypt before that.

**Comment by jjakob** [comment]
Shouldn't be an issue, the patching part where it fails is before we even get to running letsencrypt or deploying the certificates. Deploying letsencrypt certs over self-signed is an interesting test case however.

**Comment by eN0Rm** [comment]
Just adding that we also run zimbra on Ubuntu 14.04 

Release 8.8.8.GA.2009.UBUNTU14.64 UBUNTU14_64 FOSS edition, Patch 8.8.8_P4.

**Comment by eN0Rm** [comment]
Would this work if translated to sed? This is a search and replace in vim

:%s/^}/\r    location \^\~ \/.well-known\/acme-challenge { \r         root \/opt\/zimbra\/data\/nginx\/html;\r    }\r}/gc

**Comment by eN0Rm** [comment]
I just made a fork you your repository and hacked it so it worked for me.

**Comment by jjakob** [comment]
Sorry I haven't been able to work on this before now. Since the changes are merged in https://github.com/YetOpen/certbot-zimbra I'm closing this. I'll push further changes to there too so that there aren't unnecessary forks and issues at different places.
